/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 22 13:52:21 GMT 2019
 */

package org.jfree.chart.plot;

import org.junit.Test;
import static org.junit.Assert.*;
import java.awt.Color;
import java.awt.Stroke;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfree.chart.plot.ValueMarker;
import org.jfree.chart.renderer.category.StatisticalBarRenderer;
import org.junit.runner.RunWith;


public class ValueMarker_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ValueMarker valueMarker0 = new ValueMarker((-493.479486469));
      double double0 = valueMarker0.getValue();
      assertEquals((-493.479486469), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Color color0 = Color.blue;
      StatisticalBarRenderer statisticalBarRenderer0 = new StatisticalBarRenderer();
      Stroke stroke0 = statisticalBarRenderer0.getErrorIndicatorStroke();
      ValueMarker valueMarker0 = new ValueMarker(2969.7641375, color0, stroke0);
      assertEquals(2969.7641375, valueMarker0.getValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ValueMarker valueMarker0 = new ValueMarker(1201.2552);
      boolean boolean0 = valueMarker0.equals((Object) null);
      assertEquals(1201.2552, valueMarker0.getValue(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ValueMarker valueMarker0 = new ValueMarker(1201.2552);
      ValueMarker valueMarker1 = (ValueMarker)valueMarker0.clone();
      boolean boolean0 = valueMarker0.equals(valueMarker1);
      assertEquals(1201.2552, valueMarker1.getValue(), 0.01);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ValueMarker valueMarker0 = new ValueMarker(1201.2552);
      Object object0 = valueMarker0.clone();
      valueMarker0.setValue(2.5E11);
      boolean boolean0 = valueMarker0.equals(object0);
      assertEquals(2.5E11, valueMarker0.getValue(), 0.01);
      assertFalse(boolean0);
  }
}
