/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 11 19:37:39 GMT 2014
 */

package com.google.javascript.jscomp;

import static org.junit.Assert.*;
import org.junit.Test;
import com.google.javascript.jscomp.TypeInference;
import com.google.javascript.rhino.jstype.BooleanLiteralSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;

import org.junit.runner.RunWith;


public class TypeInferenceEvoSuite_branch_Test  {

  @Test
  public void test0()  throws Throwable  {
      BooleanLiteralSet booleanLiteralSet0 = BooleanLiteralSet.EMPTY;
      boolean boolean0 = false;
      BooleanLiteralSet booleanLiteralSet1 = TypeInference.getBooleanOutcomes(booleanLiteralSet0, booleanLiteralSet0, boolean0);
      assertEquals(BooleanLiteralSet.EMPTY, booleanLiteralSet1);
      assertSame(booleanLiteralSet0, booleanLiteralSet1);
      assertSame(booleanLiteralSet1, booleanLiteralSet0);
      assertEquals(0, booleanLiteralSet1.ordinal());
      assertEquals("EMPTY", booleanLiteralSet1.name());
      assertEquals("EMPTY", booleanLiteralSet1.toString());
  }

  @Test
  public void test1()  throws Throwable  {
      BooleanLiteralSet booleanLiteralSet0 = BooleanLiteralSet.BOTH;
      boolean boolean0 = true;
      BooleanLiteralSet booleanLiteralSet1 = TypeInference.getBooleanOutcomes(booleanLiteralSet0, booleanLiteralSet0, boolean0);
      assertEquals(BooleanLiteralSet.BOTH, booleanLiteralSet1);
      assertSame(booleanLiteralSet1, booleanLiteralSet0);
      assertSame(booleanLiteralSet0, booleanLiteralSet1);
      assertEquals("BOTH", booleanLiteralSet1.toString());
      assertEquals("BOTH", booleanLiteralSet1.name());
      assertEquals(3, booleanLiteralSet1.ordinal());
  }
}
